README.rst
This is not true; nixpkgs-update uses both github release information and pypi
release information in making updates.
=> Remove comment about nixpkgs-update not using github releases or pypi

nix_update/__init__.py
Updating failed if either of these return a non-zero return
code and subsequent actions (i.e. `git commit`) should not be
invoked.
=> Check return status for build/test

nix_update/update.py
SRI hashes containing regex characters such as '+'
break the replacement logic intended with `re.sub`
Use strict string replacements instead
---
nixpkgs@f0bce04b991
Before:
```
λ nix-update python3Packages.botocore --commit --build
$ git -C ./. diff --staged
$ nix eval --json --impure --experimental-features nix-command --expr (with import ./. {};
let
pkg = python3Packages.botocore;
raw_version_position = builtins.unsafeGetAttrPos "version" pkg;
position = if pkg ? isRubyGem then
raw_version_position
else
builtins.unsafeGetAttrPos "src" pkg;
in {
name = pkg.name;
old_version = (builtins.parseDrvName pkg.name).version;
inherit raw_version_position;
filename = position.file;
line = position.line;
urls = pkg.src.urls or null;
url = pkg.src.url or null;
rev = pkg.src.url.rev or null;
hash = …
```
=> Fix pattern replacements

README.rst, nix_update/__init__.py, nix_update/options.py, nix_update/update.py, nix_update/utils.py, nix_update/version/__init__.py, nix_update/version/github.py, nix_update/version/gitlab.py, nix_update/version/pypi.py, nix_update/version/rubygems.py
This can be used to remove tag prefixes, suffixes or similar
Closes #29
Allows updates of packages like `jq`.
Before:
```
λ nix-update jq --build --test
$ nix eval --json --impure --experimental-features nix-command --expr (with import ./. {};
let
pkg = jq;
raw_version_position = builtins.unsafeGetAttrPos "version" pkg;
position = if pkg ? isRubyGem then
raw_version_position
else
builtins.unsafeGetAttrPos "src" pkg;
in {
name = pkg.name;
old_version = (builtins.parseDrvName pkg.name).version;
inherit raw_version_position;
filename = position.file;
line = position.line;
urls = pkg.src.urls or null;
url = pkg.src.url or null;
rev = pkg.src.url.rev or null;
hash = pkg.src.outputHash;
mod_sha256 = pkg.modSha256 or null;
vendor_sha256 = pkg.vendorSha256 or null;
cargo_sha256 = pkg.cargoSha256 …
```
=> Allow extracting version information

README.rst, nix_update/__init__.py, nix_update/options.py, nix_update/update.py, nix_update/utils.py, nix_update/version/__init__.py, nix_update/version/github.py, nix_update/version/gitlab.py, nix_update/version/pypi.py, nix_update/version/rubygems.py, nix_update/version/version.py
Enabling this flag will include all versions
containing '-' and '+' from being considered valid.
As per SemVer, these are the separators for unstable
versions (i.e. "-RC2", "+abcdef" suffixes).
=> Add --unstable-version argument

nix_update/__init__.py
If used in combination with --commit, the changes
were previously not staged and hence left uncommitted
=> Fix --format

README.md, nix_update/eval.py
`cargoDeps` is used with [cargoSetupHook](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/hooks/cargo-setup-hook.sh) and usually [fetchCargoTarball](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/fetch-cargo-tarball/default.nix) to specify dependencies for cargo packages
`cargoHash` and `cargoSha256` would still work since they are implemented in `buildRustPackage` using `cargoDeps = fetchCargTarball {...}`
example: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/spot/default.nix
=> add support for cargoDeps

nix_update/__init__.py, nix_update/git.py, nix_update/update.py, nix_update/utils.py
this will give users more feedback, e.g. we will have a status bar from nix during `--build`
also changes the default for `run` to inherit stderr because most `run` calls don't need to capture stderr
=> inherit stdout and stderr when appropriate

nix_update/__init__.py, nix_update/eval.py, nix_update/update.py, nix_update/version/__init__.py, nix_update/version/github.py, nix_update/version/gitlab.py, nix_update/version/version.py, tests/test_branch.atom, tests/test_branch.py
This adds VersionPreference.BRANCH. By passing `--version=branch[=<name>]` the commits of branch `<name>` (`master` if ommitted) are fetched and versions `unstable-YYYY-MM-DD` are generated containing all commits up to and including this date.
This also uses Version objects instead of version number strings to allow us to pass an additional `rev` to `replace_version`.
I am not sure about the tweaks to eval.py but using nix's version parsing creates version like `unstable-unstable-YYYY-MM-DD` and `pkgs.src.url.rev` seemed like a mistake to me.
=> update unstable packages from git to latest branch

nix_update/__init__.py, nix_update/eval.py, nix_update/update.py, nix_update/version/__init__.py, tests/test_branch.py, tests/test_github.py, tests/test_gitlab.py, tests/testpkgs/default.nix, tests/testpkgs/github.nix, tests/testpkgs/gitlab.nix
Adds a diff url to the commit message similar to the changelog feature  #101, e.g.:
Diff: https://github.com/sharkdp/fd/compare/v8.0.0...v8.5.2
Diff: https://gitlab.gnome.org/world/phosh/phosh/-/compare/v0.20.0...v0.22.0
This integration tests are adapted from test_pypi in #101 as well
=> Add diff feature

nix_update/update.py, nix_update/version/__init__.py
to test, revert cargo-nextest to the 0.9.43 and run `nix-update cargo-nextest`
before: 0.9.43 -> quick-junit-0.3.2
after: 0.9.43 -> 0.9.44
=> prefer versions with the same prefix

nix_update/__init__.py
this is set by the nixpkgs updater and will make it possible to omit the `attrPath` in `nix-update-script`
=> default attribute to $UPDATE_NIX_ATTR_PATH

nix_update/eval.py
Fix the computation of the position by detecting if the pkg is a PHP extension
=> feat: let PHP extension be updatable by this tool

nix_update/update.py
so it doesn't generate broken urls for `fetchSubmodules = true`
=> remove trailing `.git` for github diff urls

nix_update/update.py
after switching away from nix-prefetch in https://github.com/Mic92/nix-update/commit/5692ffc91d61090679f74e5b6f01c87b97b816eb, nix-update no longer aborts when prefetching the hash fails: https://github.com/NixOS/nixpkgs/pull/215906#issuecomment-1427010640
=> reject empty hashes

tests/test_flake.py, tests/test_gitea.py, tests/test_github.py, tests/test_gitlab.py, tests/test_npm.py, tests/test_pypi.py, tests/test_savanna.py, tests/test_sourcehut.py
fixes broken tests due to flaky string comparisons
```python
AssertionError: assert '10.8.10' > '10.8.6'
```
bors r+
=> improve version assertions in tests

nix_update/eval.py
hopefully fixes #153 
using `toString` stops `Cargo.lock` from being copied to the store alone, and makes sure it is still under the directory of the flake, so nix-update is able to find its local path
=> fix updating cargoLock with flakes

shell.nix
It was broken due to the removal of `passthru.env` in #165, `nix-shell` will still work as it will pick up `default.nix`
=> remove shell.nix

nix_update/eval.py, nix_update/update.py
go-modules has been renamed to goModules
for nixpkgs https://github.com/NixOS/nixpkgs/pull/242905
=> support new goModules attr

nix_update/options.py
closes #178
it uses `json.dumps` which may not be the most ideal, but it is the easiest way I can think of
=> escape attribute names

nix_update/__init__.py, nix_update/eval.py, nix_update/options.py, nix_update/update.py, tests/test_flake.py, tests/test_pypi.py
In #179, I introduced a few bugs in e.g. commit messages, this should be able to fix it
=> fix attribute name escaping

nix_update/options.py, tests/test_cargo_lock_expand.py, tests/test_cargo_lock_update.py, tests/testpkgs/default.nix
=> fix escaping for non-toplevel attributes

nix_update/update.py, nix_update/version/__init__.py, nix_update/version/bitbucket.py, tests/test_bitbucket.py, tests/testpkgs/bitbucket.nix, tests/testpkgs/default.nix
Add support for bitbucket.org / bitbucket.io for tags (versions) and snapshots (latest commit by date)
=> Support bitbucket.org

README.md
Update the README to precise that the software is also in the latest stable channel, currently 23.11, shows that it has version 1.0.0 of nix-update (https://search.nixos.org/packages?channel=23.11&show=nix-update&from=0&size=50&sort=relevance&type=packages&query=nix-update)
=> Update README.md to precise that software is available in latest stable channel (23.11 as of today)

.gitignore, README.md, nix_update/eval.py, nix_update/update.py, tests/test_composer.py, tests/testpkgs/composer.nix, tests/testpkgs/default.nix
Fixed tests in https://github.com/Mic92/nix-update/pull/211
=> Add support for updating buildComposerProject's vendorHash

nix_update/version/gitlab.py
If a GitLab repository has the "Releases" feature disabled (such as [vcard](https://gitlab.com/engmark/vcard)), the updater currently fails with `KeyError: 'release'` since the release key is removed from the API
This allows it to gracefully fall back to using tags even if releases are disabled
=> make gitlab updater work by tag when releases are disabled

nix_update/__init__.py, nix_update/eval.py
This patch scraps the maintainers list from the package's metadata and displays it.
When making a PR for updating a package, one has to tag the maintainers. Thus, I always find myself manually opening the source file of the package I update just to check the names of the maintainers.
Furthermore, their github handles are not always the same as their name and sometimes have to be looked up for in `maintainers/maintainer-list.nix`.
```
...
maintainers = pkg.meta.maintainers or null;
changelog = pkg.meta.changelog or null;
} --extra-experimental-features flakes nix-command
fetch https://github.com/astral-sh/ruff-lsp/releases.atom
Not updating version, already 0.0.50
Package maintainers:
- figsoda (@figsoda)
- Konstantin Alekseev (@kalekseev)
$ git -C /home/gaetan/perso/nix/nixpkgs diff -- …
```
=> print maintainers list

nix_update/update.py
This fixes running `nix-update` on cargo lock packages leaving result links laying around
=> make cargo lock updater keep outpath links in temporary directory

nix_update/version/gitlab.py
=> Fix fetching GitLab snapshots on repos with no tags

nix_update/eval.py
Some package builders set `meta.position` manually due to clobbering the origin of `src`.
Fixes `nix-update -u mpvScripts.*`, discovered while reviewing https://github.com/NixOS/nixpkgs/pull/308062.
=>  Try pkg.meta.position before unsafeGetAttrPos

README.md, default.nix, flake.lock, nix_update/__init__.py, nix_update/version/__init__.py
following [rfc 166](https://github.com/NixOS/rfcs/pull/166), [nixfmt](https://github.com/NixOS/nixfmt) is now the official formatter for nix and slowing becoming more commonplace in both nixpkgs and the community. though it isn't stable just yet, i think it might be good to start using it sooner rather than later
=> use `nixfmt` with `--format`

flake.lock, flake.nix, nix_update/eval.py, nix_update/update.py, tests/test_pnpm.py, tests/testpkgs/default.nix, tests/testpkgs/pnpm.nix
Now that https://github.com/NixOS/nixpkgs/pull/290715, it would be nice to have some update tooling :D
You can test this with the package `pot`, as it is one patch version behind on master.
https://github.com/pot-app/pot-desktop/releases
=> Add support for updating pnpmDeps

nix_update/version/__init__.py
Some packages use the `-prerelease` tag to indicate prereleases, and that's not currently detected by the `is_unstable` pattern. Here's a sample PR where the bot tries to update to a prerelease with this pattern: https://github.com/NixOS/nixpkgs/pull/306846
=> version: add prerelease to unstable pattern

nix_update/update.py
As `update_cargo_lock()` overrides the top level derivations, this will cause hash mismatch errors in the event of other FODs being used in the environment (i.e., `pnpmDeps`) during updates if they also need to be updated. `gitbutler` in nixpkgs at [this](https://github.com/NixOS/nixpkgs/tree/e6e4cd92ad886b91a6de120ce61c81b7e6072530/pkgs/by-name/gi/gitbutler) revision is a real world example of this occurring, and changing the order of these function calls allows it to run as expected
=> update Cargo.lock after other hashes

README.md, nix_update/eval.py, nix_update/update.py, tests/test_mix.py, tests/testpkgs/default.nix, tests/testpkgs/mix.nix
Happy to move things around, rename, document differently. This adds support for automatically updating the `mixFodDeps` hash used by `beamPackages.mixRelease`.
Thanks for the handy update script!
=> Add support for updating Mix dependencies for Elixir projects

nix_update/eval.py
`meta.position` is prone to point at files where `src` and `version` is not contained, as is the case for overridden packages and packages that use a generic builder.
There is also the fix explored in https://github.com/NixOS/nixpkgs/pull/329900 and https://github.com/NixOS/nixpkgs/pull/295973, which would alleviate many of the errors while creating new ones.
Fixes https://github.com/Mic92/nix-update/pull/247#issuecomment-2281135694
=> Try pkg.meta.position after unsafeGetAttrPos

README.md, nix_update/__init__.py, nix_update/options.py, nix_update/update.py, tests/test_cargo_lock_generate.py, tests/testpkgs/cargo-lock-generate/simple/default.nix, tests/testpkgs/cargo-lock-generate/with-lockfile-metadata-path/default.nix, tests/testpkgs/default.nix
closes https://github.com/Mic92/nix-update/issues/164
The problems with vendored Cargo.lock to nixpkgs are discussed in the following [issue](https://github.com/NixOS/nixpkgs/issues/327063), but for now it would be a good idea to allow such Cargo.lock to be updated with nix-update.
There are many projects, especially in python packages, that have no Cargo.lock, and we feel painful updating them for a while until the issue is resolved.
=> Add support for generating Cargo.lock

nix_update/update.py, tests/testpkgs/cargo-lock-generate/simple/default.nix, tests/testpkgs/cargo-lock-generate/with-lockfile-metadata-path/default.nix
* don't assume we have a nix flake registry instead take cargo from the build
* set experimental flags
* apply patches to build
=> make updating cargo.lock more robust

nix_update/update.py, tests/test_cargo_lock_generate.py, tests/testpkgs/cargo-lock-generate/with-lockfile-metadata-path-outside-workspace/default.nix, tests/testpkgs/default.nix
This is a follow-up PR for https://github.com/Mic92/nix-update/pull/266.
If Cargo.toml is outside a workspace, Cargo.lock is generated in the same directory as Cargo.toml.
The current implementation expects Cargo.lock to be in the project root, so the update fails.
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpn_dgfq0d/Cargo.lock'`
=> fix handling of cargo.lock outside a workspace

README.md, nix_update/__init__.py, nix_update/options.py, nix_update/update.py
This allows you to skip the prompt when using `-u`, nice to have when scripting `nix-update`
```
nix-update sbt --use-update-script --update-script-args "--argstr skip-prompt true"
```
=> Add --update-script-args

flake.lock, treefmt.nix
The current nixpkgs is quite old and doesn't have `php.buildComposerProject2`, which is needed for https://github.com/Mic92/nix-update/pull/283.
Also fixed a parameter to ruff, since the old one was removed and no longer worked.
=> Update flake lock

nix_update/eval.py, nix_update/update.py, tests/test_composer_old.py, tests/testpkgs/composer-old.nix, tests/testpkgs/default.nix
[A new version of `buildComposerProject`](https://github.com/NixOS/nixpkgs/pull/308059) has been introduced. Updating packages that use this new version with nix-update failed to update the `vendorHash` before this PR.
=> Add support for new Composer builder

default.nix, flake.lock, pyproject.toml, tests/test_cargo_lock_update.py, tests/test_flake.py, tests/testpkgs/cargo-lock-update/default.nix, tests/testpkgs/crate.nix, tests/testpkgs/flake.nix
This is a preliminary PR before adding support for the new cargo vendor fetcher.
- **cosmetic fixes to default.nix**
- **flake.lock: Update**
- **test_flake: add diff assertion**
- **format codebase with nixfmt**
- **test_cargo_lock_update: use more recent version of ruff**
- **testpkgs/crate.nix: cargoSha256 -> cargoHash**
=> miscellaneous cleaning

README.md, nix_update/update.py, tests/test_update.py, tests/testpkgs/default.nix, tests/testpkgs/let-bound-version.nix, tests/testpkgs/set.nix
Prior to this change, nix-update would update all version strings which were equal to the specified package to update. Now, only the version line of the specified package will be updated.
=> Fix updating all matching version numbers

README.md, nix_update/update.py, tests/test_npm_lock_generate.py, tests/testpkgs/default.nix, tests/testpkgs/npm-lock-generate/default.nix
- **feat: add support for generating package-lock.json**
- **refactor: unify lockfile generation functions**
Combine cargo and npm lockfile generation into a single function `generate_lockfile` use parameters to handle different types and configurations reduce code duplication and improve maintainability.
=> feat: add support for generation package-lock.json

README.md, nix_update/__init__.py, nix_update/options.py, nix_update/update.py, tests/test_subpackage.py, tests/testpkgs/default.nix, tests/testpkgs/subpackage.nix
Adds an option for users to specify subpackages that `nix-update` should also look at. `nix-update` will evaluate these sub-derivations after updating the package's version and source, but before trying to evaluate the package's main derivation. This allows for subpackages that are depended upon by the main package build.
Not included is any sort of accommodation for sub-subpackages. I hope those do not occur often in real builds.
Closes #310.
=> feat: add `--subpackage` option to update multiple derivations

README.md, flake.lock, nix_update/eval.py, nix_update/update.py, nix_update/version/__init__.py, nix_update/version/version.py, tests/test_github.py, tests/testpkgs/default.nix, tests/testpkgs/github-tag.nix
Mainly opening this to avoid duplicated work as I see more people want this feature.
I don't have much time right now, but I can probably finish it in a day.
Closes https://github.com/Mic92/nix-update/issues/304, https://github.com/NixOS/nixpkgs/issues/367562
=> feat: tag in fetchFromGitHub support

nix_update/update.py, tests/test_version_regex_no_rev.py, tests/testpkgs/default.nix, tests/testpkgs/net-news-wire.nix
When using `--version-regex` on a package the fetches source via `fetchurl` the update failed because `package.rev` was `None`
=> fix `fetchurl` with `--version-regex`

nix_update/__init__.py
Fixes #316
Tested by invoking the newly built nix-update as `nix-update --option extra-experimental-features pipe-operators --commit --build` on a package that uses the pipe operator and previously failed to evaluate.
=> feat: add --option argument

nix_update/__init__.py, nix_update/options.py, nix_update/update.py, tests/test_src_only.py
Context: last few comments in https://github.com/Mic92/nix-update/pull/320 (this flag was initially mentioned as `--skip-deps`,  `--dont-update-deps` or `--no-fetch-deps` that would've only applied to `nugetDeps`)
In some cases you want to use nix-update's logic where it can fetch the latest version and hash from various sources, but don't want to update dependencies like `nugetDeps`, `npmDeps`, `cargoDeps`, etc. Currently the solution for this in nixpkgs is making a request to the GitHub API or other sources, and using `update-source-version` to update the version, then manually do the deps update part.
Instead of writing 
```bash
new_version="$(curl -s "https://api.github.com/repos/AvaloniaUI/Avalonia/releases/latest" | jq --raw-output '.tag_name')"
update-source-version avalonia …
```
=> feat: add --src-only flag

nix_update/version/rubygems.py
```
} --extra-experimental-features flakes nix-command
fetch https://rubygems.org/api/v1/versions/bundler.json
Traceback (most recent call last):
File "/nix/store/2dk7xil4ing93997lx1y4rgda5s2zmwv-nix-update-1.7.0/bin/.nix-update-wrapped", line 9, in <module>
sys.exit(main())
^^^^^^
File "/nix/store/2dk7xil4ing93997lx1y4rgda5s2zmwv-nix-update-1.7.0/lib/python3.12/site-packages/nix_update/__init__.py", line 311, in main
package = update(options)
^^^^^^^^^^^^^^^
File "/nix/store/2dk7xil4ing93997lx1y4rgda5s2zmwv-nix-update-1.7.0/lib/python3.12/site-packages/nix_update/update.py", line 463, in update
update_hash = update_version(
^^^^^^^^^^^^^^^
File "/nix/store/2dk7xil4ing93997lx1y4rgda5s2zmwv-nix-update-1.7.0/lib/python3.12/site-packages/nix_update/update.py", line 397, in update_version …
```
=> fix typo in code

nix_update/update.py, tests/test_cargo_lock_generate.py, tests/test_cargo_vendor_deps.py, tests/test_fetchurl_github_release.py, tests/testpkgs/default.nix, tests/testpkgs/fetchurl-github-release.nix
The diff link in the generated commit message was broken in some cases, most notably containing `None`, missing/adding extra `v` as a version prefix.
Fixes https://github.com/NixOS/nixpkgs/issues/394072
- when there was a github link, previously it expected `fetchFromGitHub`, so it tried to read `src.rev` or  `src.tag` which doesn't exist when using plain `fetchurl`
- when the user specifies a fixed version, eg. `--version 11.41` (without a version prefix), it expected that the the tag/rev is called exactly that, but it can be `v11.41` or with other prefix
The solution is rather hacky and it's limited to github, there are multiple factors that make it hard to implement correctly:
- unclear division between user provided version, version got from eval, version got from fetching
- …
=> Improve diff url with github

nix_update/eval.py, nix_update/update.py, tests/conftest.py, tests/test_flake.py, tests/testpkgs/crate.nix
1. like the title says, I made it possible to use `--use-update-script` with flake packages. However, I've never used that flag outside of my personal use so I'm really unsure if I implemented correctly
2. Added `--commit-message` flag to print the commit message to stdout
3. Added `--quiet` flag to suppress logs of subprocesses and stuff
=> Support --use-update-script with flake packages

nix_update/version/npm.py, tests/test_npm_fetch_latest_version.py
If derivation's src is from a npm package and if such npm package is scoped (e.g. `@org/packagename` instead of `packagename`), wrong URL would be used to fetch latest version and failed.
To reproduce:
```sh
> cat test-scoped-npm.nix
{
pkgs ? import <nixpkgs> { },
}:
{
claude-code = pkgs.stdenv.mkDerivation rec {
pname = "claude-code";
version = "1.0.42";
src = pkgs.fetchurl {
url =
"https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-${version}.tgz";
sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
};
};
}
> ./bin/nix-update --file test-scoped-npm.nix claude-code
fetch https://registry.npmjs.org/@anthropic-ai/latest
Traceback (most recent call last):
File "/Users/limouren/nix-update/./bin/nix-update", line 12, in <module>
main()
~~~~^^
File …
```
=> Fix wrong URL being fetched for npm's scoped package

nix_update/version/__init__.py, tests/test_version_regex_no_rev.py, tests/testpkgs/default.nix, tests/testpkgs/postgresql.nix
This supports multiple capture groups in the `--version-regex` option. The groups will be concatenated to a single version delimited by `.`. This allows extracting versions from versioning schemes such as PostgreSQL's, which use `REL_17_0` tags etc., i.e. they use a different separator.
=> support multiple capture groups in version-regex

nix_update/update.py
Originally, the source was copied with 444/555 perms, like it was in the store.
Fixes #379 
> [!CAUTION]
> Only tested on Cargo packages, can't promise the same for Go or others
=> fix(update.py): add write perms to lockfile when generating it

tests/test_nuget_deps_generate.py
When updating dotnet packages, I used for example `nix-shell maintainers/scripts/update.nix --argstr package osu-lazer --argstr commit true` with an alias which works well.
Trying to replicate the same with `nix-update -u --commit osu-lazer` won't exactly work, it will leave the changed `deps.json` file uncomitted, this is what I'd like to fix, in this PR I only added a test for it.
`nix-update` currently detects changed files "manually" for each package, for example when updating the `chit` rust package that has `cargoLock.lockFile = ./Cargo.lock`, that path can be queried with `nix eval -f . chit.cargoDeps.lockFile` => `/home/gep/nixpkgs/pkgs/by-name/ch/chit/Cargo.lock`.
However for dotnet I couldn't find a similar function: in the `osu-lazer` dotnet package that has `nugetDeps = …
=> test: add nuget-deps-generate assert for deps.json being comitted

nix_update/version/github.py, tests/test_github.py, tests/testpkgs/default.nix, tests/testpkgs/github-forcefetchgit.nix
This also switches owner to lazy matches for consistency.
Fixes: 077f4cfaa48a97d65ab161cc3253218f69f88c29
=> github.py: fix removal of .git suffix from repo

tests/test_savanna.py, tests/testpkgs/savanna.nix
It got removed in https://github.com/NixOS/nixpkgs/pull/305197 with gamin and now eval fails which fails the test.
This is required to create a new release.
=> Replace savanna test package with one that actually exists

nix_update/version/gitea.py
Hi,
On Forgejo at least, some instances might only have a signing-key.ssh.
=> change Gitea detection url
