Mic92/nix-update

README.rst
Also, use --version and not only [version] in usage.
I missed this info as a first time user.
=> README: better explain the known bugs

default.nix, nix_update/__init__.py, nix_update/eval.py, nix_update/utils.py
This was adding too much boiler code.
Having one version is easier to maintain.
=> always assume nix flakes enabled version

nix_update/__init__.py, nix_update/eval.py, nix_update/options.py, nix_update/utils.py
Closes #24 
This is sort of what I had in mind to add testing.
Might need some `is_nix_flakes()` love, I am not super familiar with that.
=> Add test flag

nix_update/update.py
This is going to require an opinion, I think :)
I don't know if you have a use case for updates that only change the hash (seems weird to me but maybe there is a reason).
Anyways, I have a use case against that:
Maintainers on different nix versions currently swap between the old SHA256 and the new notation.
This confuses `nix-update` and triggers commits that purely change the hash format (but get committed as `PACKAGE: 1.2.3 -> 1.2.3` with `--commit`).
This change will not trigger hash changes if the version has not been updated.
=> Skip updating hashes without version change

nix_update/update.py
=> fix UnboundLocalError

README.rst, default.nix, nix_update/__init__.py, nix_update/options.py
- Integrate with `nixpkgs-review`
- Skip attempts to run review, test or commit if no changes have been detected
=> Add --review flag

README.rst, default.nix, nix_update/__init__.py, nix_update/options.py
The flag will invoke nixpkgs-fmt
=> Add --format flag

default.nix, nix_update/update.py, setup.cfg, tests/conftest.py, tests/test_pypi.py, tests/testpkgs/pypi.nix
Now nix-update also works when config.checkMeta is true.
=> Turn of checkMeta for nix-prefetch

nix_update/version/__init__.py, nix_update/version/savannah.py, tests/test_savanna.py, tests/testpkgs/default.nix, tests/testpkgs/savanna.nix
Add a new fetcher that parses [Savannah's](https://download.savannah.nongnu.org/releases/) directory listing.
=> add support for mirror://savannah/

nix_update/eval.py
fixes https://github.com/Mic92/nix-update/issues/62
=> fix evaluation on macos for pkgs with tests

default.nix
the broken wrapper on my side is caused by something else
=> Drop python3 again

shell.nix
Sadly doesn't work in 21.11 but I am not good enough with nix to make it work.
=> Use mkShellNoCC

README.md, nix_update/update.py, nix_update/version/__init__.py, nix_update/version/crate.py, tests/test_crate.py, tests/testpkgs/crate.nix, tests/testpkgs/default.nix
fixes #47 
mostly copied from pypi support
=> add fetchCrate support

.github/workflows/test.yml, flake.lock, flake.nix
also switched the nixpkgs branch from master to nixos-unstable for the flake and updated the lock file
=> Use the new nix command in ci

.github/workflows/nix-fmt-checks.yaml, default.nix, flake.nix, tests/testpkgs/default.nix
=> Add `formatter` attribute with `nixpkgs-fmt`

default.nix, flake.lock
the bug that caused #128 has now been fixed upstream and updated in nixos-unstable
=> add bin/nix-update back to ruff checks

.github/workflows/test.yml, README.md, nix_update/__init__.py, nix_update/eval.py, nix_update/options.py, nix_update/update.py
=> add --system

.github/workflows/nix-fmt-checks.yaml, README.md, bors.toml, nix_update/update.py, nix_update/version/__init__.py, nix_update/version/gitea.py, tests/test_gitea.py, tests/testpkgs/default.nix, tests/testpkgs/gitea.nix
=> gitea support

default.nix, flake.lock
=> fix build with updated nixpkgs

.github/workflows/test.yml
=> ci: only build on certain branches

nix_update/__init__.py, nix_update/update.py
=> consider revision when checking whether there was an update

nix_update/eval.py
=> remove unused code

nix_update/eval.py
=> improve assertion message

.github/workflows/nix-fmt-checks.yaml
=> make treefmt check fail on change

nix_update/__init__.py
fixes https://github.com/Mic92/nix-update/issues/170
=> git-commit files directly without using staging area

nix_update/__init__.py, nix_update/eval.py, nix_update/options.py, nix_update/update.py
=> quote `import_path` when importing in nix

README.md, nix_update/eval.py, nix_update/update.py
For https://github.com/NixOS/nixpkgs/pull/140701
=> support for updating yarn FOD hash

README.md
closes https://github.com/Mic92/nix-update/issues/223
=> document how to update a flakes legacyPackages

nix_update/eval.py, tests/testpkgs/sourcehut.nix
fixes https://github.com/Mic92/nix-update/issues/238
=> respect --override-filename flag for flakes

nix_update/version/__init__.py, nix_update/version/gitea.py, pyproject.toml, tests/test_savanna.py
To allow self-hosted Gitea instances
Closes https://github.com/Mic92/nix-update/issues/257
=> Add check whether a host is a Gitea instance to fetcher

README.md
See https://github.com/NixOS/nixpkgs/pull/324401#discussion_r1664866850
=> README: Clarify that nix-update *does* update Cargo.lock files

nix_update/version/github.py, tests/test_github.py, tests/testpkgs/default.nix, tests/testpkgs/github-no-release.nix
=> github: Add fallback to atom feed if project does not use releases

default.nix, flake.lock, treefmt.nix
Just use whatever nixpkgs has by default
=> unpin python 3.11

nix_update/eval.py, nix_update/update.py
=> feat: support yarnOfflineCache

nix_update/__init__.py, nix_update/eval.py, nix_update/git.py, nix_update/options.py, nix_update/update.py, nix_update/utils.py, nix_update/version/__init__.py, nix_update/version/bitbucket.py, nix_update/version/crate.py, nix_update/version/gitea.py, nix_update/version/github.py, nix_update/version/gitlab.py, nix_update/version/npm.py, nix_update/version/pypi.py, nix_update/version/rubygems.py, nix_update/version/savannah.py, nix_update/version/sourcehut.py
Part of https://github.com/Mic92/nix-update/pull/330
=> Add quiet flag + print-commit-message flag

nix_update/__init__.py
Update scripts sometimes change related files like Cargo.lock or
package-lock.json.
Fixes #325
=> fix: add changed files from the same folder

bin/create-release.sh
=> create-release: don't run tests locally as well
